volumes:
  ecomm_api_local_postgres_data: {}
  ecomm_api_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ecomm_api_local_django
    container_name: ecomm_api_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: ecomm_api_production_postgres
    container_name: ecomm_api_local_postgres
    volumes:
      - ecomm_api_local_postgres_data:/var/lib/postgresql/18/docker
      - ecomm_api_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:7
    container_name: ecomm_api_local_redis
    ports:
      - '6379:6379'

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: ecomm_api_local_django
    container_name: ecomm_api_local_celery_worker
    depends_on:
      - postgres
      - redis
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: celery -A ecomm_api.celery_app worker --loglevel=info